### ISSUE TITLE
How to extend more details in WebElement type?

### ISSUE THREAD

**Issue by ansonliao** [elisarver/selophane#28]
@elisarver @opensource21 , 

Thanks for sharing great extending custom WebElement project.

I would like to ask help from you on how to extend more detail on WebElement, if I can get some help from you it would be great help to me.

I would like a add a element's description field to describe the element so that it can be used in test report and make test report more detail and easier to track if fail.

for example, add a `String` field to `Element`:

``` java
public interface Element extends WebElement, WrapsElement, Locatable {
    String description;
    boolean elementWired();

    void setDescription();
    String getDescription();
}
```

Then add a new annotation `@Description` works with `@FindBy`:

``` java
public class LoginPageObjs {
    ...
    @FindBy(name = "submit")
    @Description("Login Page: [Submit] Button")
    public Element submitButton;
}
```

so that, we can use element's description to log test operation in more detail:

``` java
public void click(Element e) {
    e.click();
    // log test operation to test report, for example ReportNG
    reporter.log("Click: " + e.getDescription())     //"Click : Login Page - [Submit] Button" will be logged to test report
}
```

I would like to know, how to initialise `@Description` to the `Element` object by `PageFactory.initElements` method and `ElementFieldDecorator.java`?

**Comment by elisarver** [comment]
Something might be done with .toString describing the element instead of returning the generic element description.

Though I have to say, the stacktrace does a better job of describing the precise location in the source that a test fails, and then from there, an IDE can look up the description and get to the precise definition of the object.

The goal of Celophane is not to be a general purpose framework for testing and reporting, and is instead meant to be a minimal helping library for annotating elements with behavior that is implemented as wrapping classes. I'm often resistant to changes that run tangental to that underlying purpose.

I might be able to make such a delegating class that does this sidecar annotation on objects, but it would take some time and thought to make it useful for things that have nothing to do with web elements and make it more useful in general.

**Comment by opensource21** [comment]
@ansonliao : I fear your wish is out of the scope of selophane. You can look at [JTAF-Ext-Webdriver](http://finraos.github.io/JTAF-ExtWebDriver/about.html) which I can't recommend, because the development isn't active enough. Furthermore a German company released [WebTester](https://github.com/testIT-WebTester). It was successful in commercial context. How ever I didn't try it out, because it's relative new. The last time I looking in detail at selenium I developed [WebTest](https://github.com/opensource21/webtest) which based on JTAF-Ext-Webdriver and Selophane.
Webtest can be seen in action at the [FuWeSta-Sample](https://github.com/opensource21/fuwesta/tree/master/fuwesta-sample/src/test/java/de/ppi/samples/fuwesta/selophane/test).  In WebTest there is a UniqueElementLocator which supports fieldinformation. So you have the basic infrastructure. Unfortunately I didn't have a public example. You can look at [BasePage](https://github.com/opensource21/fuwesta/blob/19f12e450fe931690e5e9f33ff04f0a853a408d8/fuwesta-sample/src/test/java/de/ppi/samples/fuwesta/selophane/base/BasePage.java#L75) to get usage of it.
I hope it helps you a little bit.
